# Generated by Django 4.2.11 on 2024-03-21 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_name', models.CharField(max_length=200)),
                ('prod_desc', models.CharField(max_length=200)),
                ('prod_price', models.IntegerField()),
                ('prod_image', models.CharField(default='https://as1.ftcdn.net/v2/jpg/04/03/20/18/1000_F_403201859_h1aAKEUJ62VzYwMRZTpIdembpangRcCz.jpg', max_length=500)),
            ],
        ),
    ]
